/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rockstr99.config_manager_be.contract.api.v1;

import com.rockstr99.config_manager_be.contract.model.v1.CreateRuleRequest;
import com.rockstr99.config_manager_be.contract.model.v1.CreateRuleResponse;
import com.rockstr99.config_manager_be.contract.model.v1.GetRuleResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-30T00:58:12.034823200+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "rule", description = "the rule API")
public interface RuleApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /rule : Create a new Rule
     *
     * @param createRuleRequest rule details (optional)
     * @return successful response (status code 200)
     */
    @Operation(
        operationId = "createRule",
        summary = "Create a new Rule",
        tags = { "Rule" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  CreateRuleResponse.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/rule",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<CreateRuleResponse> createRule(
        @Parameter(name = "CreateRuleRequest", description = "rule details", schema = @Schema(description = "")) @Valid @RequestBody(required = false) CreateRuleRequest createRuleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ruleName\" : \"generateJSON\", \"id\" : 10001, \"swagger\" : \"swagger example\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /rule : Fetch a rule
     *
     * @param ruleName Rule Name for filter (optional)
     * @return successful response (status code 200)
     */
    @Operation(
        operationId = "getRule",
        summary = "Fetch a rule",
        tags = { "Rule" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successful response", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  GetRuleResponse.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/rule",
        produces = { "application/json" }
    )
    default ResponseEntity<GetRuleResponse> getRule(
        @Parameter(name = "ruleName", description = "Rule Name for filter", schema = @Schema(description = "")) @Valid @RequestParam(value = "ruleName", required = false) String ruleName
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ruleName\" : \"generateJSON\", \"id\" : 10001, \"swagger\" : \"swagger example\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
